[SchemaRegistryData]
USE = true
PATH = 
XML = SchemaRegistryData.xml

[Components]
Count = 6

;그 외 관리자 실행
;*RTICommunicationManager가 후반부에 실행
;CommandManager는 가장 마지막에 실행

[Component_1]
PATH = FooManager
DLL = FooManager
XML = FooManager.xml
POWER = on

[Component_2]
PATH = BarManager
DLL = BarManager
XML = BarManager.xml
POWER = on

[Component_3]
PATH = RTICommunicationManager
DLL = RTICommunicationManager
XML = RTICommunicationManager.xml
POWER = off

[Component_4]
PATH = UDPCommunicationManager
DLL = UDPCommunicationManager
XML = UDPCommunicationManager.xml
POWER = off

[Component_5]
PATH = TCPCommunicationManager
DLL = TCPCommunicationManager
XML = TCPCommunicationManager.xml
POWER = off

[Component_6]
PATH = CommandManager
DLL = CommandManager
XML = CommandManager.xml
POWER = on



