[SchemaRegistryData]
USE = true
PATH =
XML = SchemaRegistryData.xml
CheckMsgIDDuplication = true

[nLogger]
USE = true

[ValidatingComponents]
USE = true
MetadataFullValidation = false

[Components]
Count = 5

; SAMS OC Manager 구성
; Execution order: UDPCommunicationManager -> ScenarioManager -> SimulationManager -> EngagementManager -> UIManager

[Component_1]
PATH = UDPCommunicationManager
DLL = UDPCommunicationManager
XML = UDPCommunicationManager.xml
POWER = on

[Component_2]
PATH = ScenarioManager
DLL = ScenarioManager
XML = ScenarioManager.xml
POWER = on

[Component_3]
PATH = SimulationManager
DLL = SimulationManager
XML = SimulationManager.xml
POWER = on

[Component_4]
PATH = EngagementManager
DLL = EngagementManager
XML = EngagementManager.xml
POWER = on

[Component_5]
PATH = UIManager
DLL = UIManager
XML = UIManager.xml
POWER = on
