[LOCAL]
IP =127.0.0.1
PORT =10000

[REMOTE]
IP =127.0.0.1
PORT =20000

[SERVICE]
PROTOCOL =UDP
;TCP, UDP
ROLE = SEND
;SEND, RECEIVE
CAST =UNICAST
;NS UNICAST, MULTICAST , BROADCAST

[HEADER]
SIZE = 12
ID_POS = 0
ID_SIZE = 2
LEN_POS = 2
LEN_SIZE = 2
