[SchemaRegistryData]
USE = true
PATH = 
XML = SchemaRegistryData.xml

[nLogger]
USE = true

[ValidatingComponents]
USE = true

[Components]
Count = 3

; RSS runtime components only.

[Component_1]
PATH = UDPCommunicationManager
DLL = UDPCommunicationManager
XML = UDPCommunicationManager.xml
POWER = on

[Component_2]
PATH = RSSManager
DLL = RSSManager
XML = RSSManager.xml
POWER = on

[Component_3]
PATH = SimulationManager
DLL = SimulationManager
XML = SimulationManager.xml
POWER = on
