[LOCAL]
IP =192.168.0.104
PORT =10000

[REMOTE]
IP =192.168.0.101
PORT =10000

[MULTICAST]
IP =239.10.10.10
PORT =10000

[BROADCAST]
IP =255.255.255.255
PORT =10000

[SERVICE]
PROTOCOL =UDP
;TCP, UDP
ROLE =SEND
;SEND, RECEIVE
CAST =MULTICAST
;NS UNICAST, MULTICAST , BROADCAST

[HEADER]
SIZE = 4
ID_POS = 0
ID_SIZE = 2
LEN_POS = 2
LEN_SIZE = 2


